'use client';

import { useState, useEffect } from 'react';
import { BookOpen, Sparkles, Loader2, Brain } from 'lucide-react';
import ReactMarkdown from 'react-markdown';

interface DatabaseExplainerProps {
  schema: Record<string, any[]>;
  explanationOverride?: string;
}

export default function DatabaseExplainer({ schema, explanationOverride }: DatabaseExplainerProps) {
  const [explanation, setExplanation] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Effect for Schema Explanation (only if no override)
  useEffect(() => {
    if (explanationOverride) {
      setExplanation(explanationOverride);
      return;
    }

    const generateExplanation = async () => {
      if (!schema || Object.keys(schema).length === 0) return;
      
      setLoading(true);
      setError('');
      
      try {
        const prompt = `
          Analyze the following database schema and provide a comprehensive explanation.
          
          Schema Context:
          ${JSON.stringify(schema, null, 2)}
          
          Please include:
          1. **Overview**: What is the likely purpose of this database?
          2. **Key Tables**: Explain the main tables and their roles.
          3. **Relationships**: How are the tables related? (Infer from names like _id).
          4. **Potential Use Cases**: What kind of application would use this?
          
          Format the output in clean Markdown.
        `;

        const res = await fetch('/api/ai', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ prompt, schemaContext: schema, mode: 'explain_schema' }), 
        });
        
        const data = await res.json();
        
        if (data.success) {
          setExplanation(data.explanation);
        } else {
          setError(data.message || 'Failed to generate explanation');
        }
      } catch (err: any) {
        setError(err.message || 'Failed to connect to AI service');
      } finally {
        setLoading(false);
      }
    };

    generateExplanation();
  }, [schema, explanationOverride]);

  if ((!schema || Object.keys(schema).length === 0) && !explanationOverride) {
    return (
      <div className="p-8 text-center text-gray-500">
        No schema available to explain. Please connect to a database first.
      </div>
    );
  }

  return (
    <div className="p-6 bg-gray-50 dark:bg-gray-900 h-full overflow-y-auto">
      <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-6 flex items-center gap-2">
        {explanationOverride ? <Brain className="text-purple-600" /> : <BookOpen className="text-blue-600" />}
        {explanationOverride ? 'Query Analysis' : 'Database Explainer'}
      </h2>

      {loading ? (
        <div className="flex flex-col items-center justify-center h-64 text-gray-500">
          <Loader2 size={48} className="animate-spin text-blue-500 mb-4" />
          <p className="text-lg">Analyzing...</p>
          <p className="text-sm text-gray-400 mt-2">This may take a few seconds.</p>
        </div>
      ) : error ? (
        <div className="p-6 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800 rounded-lg text-red-600 dark:text-red-400">
          <h3 className="font-bold mb-2">Error Generating Explanation</h3>
          <p>{error}</p>
        </div>
      ) : (
        <div className="bg-white dark:bg-gray-800 p-8 rounded-lg shadow border border-gray-200 dark:border-gray-700 prose dark:prose-invert max-w-none w-full min-w-0 break-words whitespace-pre-wrap [&_pre]:whitespace-pre-wrap [&_pre]:break-words">
          <div className="flex items-center gap-2 mb-6 text-purple-600 dark:text-purple-400 text-sm font-medium uppercase tracking-wider">
            <Sparkles size={16} /> Generated by AI
          </div>
          <ReactMarkdown>{explanation}</ReactMarkdown>
        </div>
      )}
    </div>
  );
}
